ICT/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from django.views.static import serve

urlpatterns = [
    path('', include('core.urls')),
    path('itech/', include('itech.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'core.views.handler404'
handler500 = 'core.views.handler500'

itech/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home_view, name='itech'),
    path('daftar', views.daftar_view, name='daftar'),
    path('daftar/valorant', views.daftar_valorant_view, name='daftar-valorant'),
    path('daftar/shortmovie', views.daftar_short_movie_view,
         name='daftar-shortmovie'),
    path('daftar/valorant/sukses', views.daftarsuksesvalorant_view,
         name='daftar-sukses-valorant'),
    path('daftar/shortmovie/sukses', views.daftarsuksesshortmovie_view,
         name='daftar-sukses-shortmovie'),
    path('about', views.about_view, name='about-itech'),
    path('juknis', views.juknis_view, name='juknis'),
    path('agenda', views.agenda_view, name='agenda'),
    path('faq', views.faq_view, name='faq'),
    path('kontak', views.kontak_view, name='kontak'),
    path('timeline', views.timeline_view, name='timeline'),
]

itech/models.py
from django.db import models

# Create your models here.


class PendaftaranValorant(models.Model):
    Nama_Tim = models.CharField(max_length=200, blank=False, null=False)
    Nomor_Whatsapp_dan_Line = models.CharField(
        max_length=200, blank=False, null=False)
    Nomor_Whatsapp_dan_Line_opsional = models.CharField(
        max_length=200, blank=True, null=True)
    Player_1 = models.CharField(
        max_length=200, blank=False, null=False)
    Nama_Lengkap_atau_Nama_Asli_1 = models.CharField(
        max_length=200, blank=False, null=False)
    Player_2 = models.CharField(
        max_length=200, blank=False, null=False)
    Nama_Lengkap_atau_Nama_Asli_2 = models.CharField(
        max_length=200, blank=False, null=False)
    Player_3 = models.CharField(
        max_length=200, blank=False, null=False)
    Nama_Lengkap_atau_Nama_Asli_3 = models.CharField(
        max_length=200, blank=False, null=False)
    Player_4 = models.CharField(
        max_length=200, blank=False, null=False)
    Nama_Lengkap_atau_Nama_Asli_4 = models.CharField(
        max_length=200, blank=False, null=False)
    Player_5 = models.CharField(
        max_length=200, blank=False, null=False)
    Nama_Lengkap_atau_Nama_Asli_5 = models.CharField(
        max_length=200, blank=False, null=False)
    Player_6 = models.CharField(
        max_length=200, blank=False, null=False)
    Nama_Lengkap_atau_Nama_Asli_6 = models.CharField(
        max_length=200, blank=False, null=False)
    Paham_dan_ingin_berpartisipasi = models.BooleanField(default=False)
    Bukti_Transaksi = models.FileField()
    Bukti_Pelajar = models.FileField(null=True)

    def __str__(self):
        return self.Nama_Tim


class PendaftaranShortMovie(models.Model):
    Nama_Kelompok = models.CharField(max_length=200, blank=False, null=False)
    Nama_Perwakilan = models.CharField(max_length=200, blank=False, null=False)
    Nama_Anggota = models.CharField(max_length=200, blank=True, null=True)
    Nomor_Whatsapp_dan_Line = models.CharField(
        max_length=200, blank=False, null=False)
    Nomor_Whatsapp_dan_Line_opsional = models.CharField(
        max_length=200, blank=True, null=True)
    Paham_dan_ingin_berpartisipasi = models.BooleanField(default=False)
    Bukti_Transaksi = models.FileField()
    Bukti_Pelajar = models.FileField(null=True)

    def __str__(self):
        return self.Nama_Kelompok

itech/forms.py
from django.forms import ModelForm
from . import models


class PendaftaranValorantForm(ModelForm):
    class Meta:
        model = models.PendaftaranValorant
        fields = ['Nama_Tim', 'Nomor_Whatsapp_dan_Line', 'Nomor_Whatsapp_dan_Line_opsional', 'Player_1', 'Nama_Lengkap_atau_Nama_Asli_1', 'Player_2', 'Nama_Lengkap_atau_Nama_Asli_2', 'Player_3', 'Nama_Lengkap_atau_Nama_Asli_3',
                  'Player_4', 'Nama_Lengkap_atau_Nama_Asli_4', 'Player_5', 'Nama_Lengkap_atau_Nama_Asli_5', 'Player_6', 'Nama_Lengkap_atau_Nama_Asli_6', 'Paham_dan_ingin_berpartisipasi', 'Bukti_Transaksi', 'Bukti_Pelajar']

    def __init__(self, *args, **kwargs):
        super(PendaftaranValorantForm, self).__init__(*args, **kwargs)
        self.fields['Nama_Tim'].widget.attrs.update(
            {'placeholder': 'Nama Tim'})
        self.fields['Nomor_Whatsapp_dan_Line'].widget.attrs.update(
            {'placeholder': 'Nomor Whatsapp dan Line'})
        self.fields['Nomor_Whatsapp_dan_Line_opsional'].widget.attrs.update(
            {'placeholder': 'Nomor Whatsapp dan Line (opsional)'})
        self.fields['Player_1'].widget.attrs.update(
            {'placeholder': 'Player 1 (ex. ICT #1234)'})
        self.fields['Nama_Lengkap_atau_Nama_Asli_1'].widget.attrs.update(
            {'placeholder': 'Nama Lengkap atau Nama Asli'})
        self.fields['Player_2'].widget.attrs.update(
            {'placeholder': 'Player 2 (ex. ICT #1234)'})
        self.fields['Nama_Lengkap_atau_Nama_Asli_2'].widget.attrs.update(
            {'placeholder': 'Nama Lengkap atau Nama Asli'})
        self.fields['Player_3'].widget.attrs.update(
            {'placeholder': 'Player 3 (ex. ICT #1234)'})
        self.fields['Nama_Lengkap_atau_Nama_Asli_3'].widget.attrs.update(
            {'placeholder': 'Nama Lengkap atau Nama Asli'})
        self.fields['Player_4'].widget.attrs.update(
            {'placeholder': 'Player 4 (ex. ICT #1234)'})
        self.fields['Nama_Lengkap_atau_Nama_Asli_4'].widget.attrs.update(
            {'placeholder': 'Nama Lengkap atau Nama Asli'})
        self.fields['Player_5'].widget.attrs.update(
            {'placeholder': 'Player 5 (ex. ICT #1234)'})
        self.fields['Nama_Lengkap_atau_Nama_Asli_5'].widget.attrs.update(
            {'placeholder': 'Nama Lengkap atau Nama Asli'})
        self.fields['Player_6'].widget.attrs.update(
            {'placeholder': 'Player 6 (cadangan)'})
        self.fields['Nama_Lengkap_atau_Nama_Asli_6'].widget.attrs.update(
            {'placeholder': 'Nama Lengkap atau Nama Asli'})
        self.fields['Paham_dan_ingin_berpartisipasi'].widget.attrs.update(
            {'placeholder': 'Saya memahami dan ingin berpartisipasi'})
        self.fields['Bukti_Transaksi'].widget.attrs.update(
            {'placeholder': 'Bukti Transaksi'})
        self.fields['Bukti_Pelajar'].widget.attrs.update(
            {'placeholder': 'Bukti Pelajar'})


class PendaftaranShortMovieForm(ModelForm):
    class Meta:
        model = models.PendaftaranShortMovie
        fields = ['Nama_Kelompok', 'Nama_Perwakilan', 'Nama_Anggota',
                  'Nomor_Whatsapp_dan_Line', 'Nomor_Whatsapp_dan_Line_opsional', 'Paham_dan_ingin_berpartisipasi', 'Bukti_Transaksi', 'Bukti_Pelajar']

    def __init__(self, *args, **kwargs):
        super(PendaftaranShortMovieForm, self).__init__(*args, **kwargs)
        self.fields['Nama_Kelompok'].widget.attrs.update(
            {'placeholder': 'Nama Kelompok'})
        self.fields['Nama_Perwakilan'].widget.attrs.update(
            {'placeholder': 'Nama Perwakilan'})
        self.fields['Nama_Anggota'].widget.attrs.update(
            {'placeholder': 'Nama Anggota [ Pisahkan dengan tanda koma (,) ] '})
        self.fields['Nomor_Whatsapp_dan_Line'].widget.attrs.update(
            {'placeholder': 'Nomor Whatsapp dan Line'})
        self.fields['Nomor_Whatsapp_dan_Line_opsional'].widget.attrs.update(
            {'placeholder': 'Nomor Whatsapp dan Line (opsional)'})
        self.fields['Paham_dan_ingin_berpartisipasi'].widget.attrs.update(
            {'placeholder': 'Saya memahami dan ingin berpartisipasi'})
        self.fields['Bukti_Transaksi'].widget.attrs.update(
            {'placeholder': 'Bukti Transaksi'})
        self.fields['Bukti_Pelajar'].widget.attrs.update(
            {'placeholder': 'Bukti Pelajar'})

itech/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render, redirect
from . import models
from .forms import PendaftaranValorantForm
from .forms import PendaftaranShortMovieForm

# Create your views here.


def home_view(request):
    contexts = {}
    return render(request, 'itech/home.html', contexts)


def about_view(request):
    contexts = {}
    return render(request, 'itech/about.html', contexts)


def juknis_view(request):
    contexts = {}
    return render(request, 'itech/juknis.html', contexts)


def agenda_view(request):
    contexts = {}
    return render(request, 'itech/agenda.html', contexts)


def faq_view(request):
    contexts = {}
    return render(request, 'itech/faq.html', contexts)


def kontak_view(request):
    contexts = {}
    return render(request, 'itech/kontak.html', contexts)


def daftar_view(request):
    context = {
    }
    return render(request, 'itech/daftar.html', context)


def daftar_valorant_view(request):
    form = PendaftaranValorantForm()

    if request.method == 'POST':
        form = PendaftaranValorantForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(to='daftar-sukses-valorant')

    context = {
        'form': form,
    }
    return render(request, 'itech/daftar-valorant.html', context)


def daftar_short_movie_view(request):
    form = PendaftaranShortMovieForm()

    if request.method == 'POST':
        form = PendaftaranShortMovieForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect(to='daftar-sukses-shortmovie')

    context = {
        'form': form,
    }
    return render(request, 'itech/daftar-shortmovie.html', context)


def daftarsuksesvalorant_view(request):
    context = {}
    return render(request, 'itech/daftar-sukses-valorant.html', context)


def daftarsuksesshortmovie_view(request):
    context = {}
    return render(request, 'itech/daftar-sukses-shortmovie.html', context)

def timeline_view(request):
    context = {}
    return render(request, 'itech/timeline.html', context)

templates/itech/about.html
{% extends 'itech/base.html' %}
{% load static %}

{% block title %}
I-Tech | Tentang
{% endblock %}

{% block body-bg %}
{% static '/itech/assets/img/bg/body-bg2.webp' %}
{% endblock %}

{% block content %}
{% include 'itech/navbar.html' %} 

  <!-- partial:index.partial.html -->

  <!-- partial:index.partial.html -->
 <div class="bg">
   <link href="https://fonts.googleapis.com/css?family=Poppins:900i" rel="stylesheet">

  <div class="title"><h4>TENTANG I-TECH</h4></div>
  <div class="dialog outer">
    <div class="dialog inner">
      Apa itu ITECH 2023?
      ITECH adalah ajang lomba tahunan yang diadakan oleh ekskul ICT MAN 4 Jakarta yang bersamaan dengan BOFMAN Part 14. Dan seperti pada tahun sebelumnya, ITECH pada tahun ini juga mengadakan lomba pertandingan game online Valorant, Shortmovie, serta adanya lomba pembuatan Poster Digital yang baru diadakan tahun ini yang mengusung tema "Escaping Technological Isolation". Tujuan dilaksanakannya pada tahun ini, ialah untuk menyalurkan hobi serta mengembangkan minat dan mutu secara kompetitif.  </div>
  </div>
  
  <div class="title"><h4>TRAILER I-TECH</h4>
  <video controls src="{% static '/itech/assets/img/iTECH2023.1.mp4' %}" width="500"></video>
  </div>
 </div>
  {% include 'itech/footer.html' %}

  {% endblock %}

templates/itech/daftar-shortmovie.html
{% extends 'itech/base.html' %}
{% load static %}

{% block title %}
I-Tech | Daftar Short Movie
{% endblock %}

{% block body-bg %}
{% static '/itech/assets/img/bg/body-bg2.webp' %}
{% endblock %}

{% block content %}
<!-- breadcrumbs area start -->
<div class="breadcrumbs_aree breadcrumbs_bg mb-140"
  data-bgimg="{% static '/itech/assets/img/bg/breadcrumbs-bg.webp' %}">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="breadcrumbs_text text-center">
          <h1>Daftar</h1>
          <ul class="d-flex justify-content-center">
            <li><a href="index.html">Home </a></li>
            <li><span>//</span></li>
            <li>Daftar</li>
            <li><span>//</span></li>
            <li>Short Movie</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- breadcrumbs area end -->
<!-- page wrapper start -->
<div class="page_wrapper">
  <!-- contact section start -->
  <section class="contact_page_section mb-140">
    <div class="container">
      <div class="row justify-content-between align-items-center mb-n50">
        <div class="col-md-8 col-12 mx-auto mb-50">
          <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="section_title text-center mb-60">
              <h2>Daftar Short Movie</h2>
              </br>
              <h4>
                Silahkan isi semua kolom dibawah dengan data yang benar
              </h4>
            </div>
            <div class="form_input">
              {{ form.Nama_Kelompok }}
            </div>
            <div class="form_input">
              {{ form.Nama_Perwakilan }}
            </div>
            <div class="form_input">
              {{ form.Nama_Anggota }}
            </div>
            <div class="form_input">
              {{ form.Nomor_Whatsapp_dan_Line }}
            </div>
            <div class="form_input">
              {{ form.Nomor_Whatsapp_dan_Line_opsional }}
            </div>
            <div class="form_input" style="margin-top: 4rem;">
              <h3>Syarat dan Ketentuan</h3>
              <p>
                1. Peserta merupakan siswa/mahasiswa per tanggal pendaftaran dan mendaftar di link
                https://ictman4jkt.com/itech/</br>
                2. Lomba dilakukan dalam bentuk tim (anggota per tim tidak dibatasi)</br>
                3. Peserta yang berada di satu tim boleh berasal dari berbagai instansi</br>
                4. Peserta wajib follow akun Instagram @ict.man4</br>
                5. Peserta wajib meng-upload poster I-TECH pada story Instagram (tag akun
                Instagram @ict.man4)</br>
                6. Biaya pendaftaran Rp60.000,00 per tim. Transfer ke Bank Mandiri 1270006135071
                a.n. Fero</br>
                7. Video harus sesuai dengan tema “Tech Reliability Improve Youth Validity” atau
                tentang bagaimana dampak teknologi dalam kinerja pemuda dan bagaimana
                pemuda memanfaatkannya</br>
                8. Short movie diproduksi tahun 2022 dan belum pernah diikutsertakan pada lomba
                lain</br>
                9. Short movie berdurasi minimal 7 menit dan maksimal 15 menit termasuk credit title</br>
                10. Video yang kurang atau lebih dari durasi yang ditentukan akan mendapatkan
                pengurangan nilai</br>
                11. Jenis short movie bebas (kecuali animasi)</br>
                12. Wajib menggunakan subtitle bahasa Indonesia bagi film yang menggunakan bahasa
                lokal atau asing</br>
                13. Setiap tim maksimal mengirimkan 1 karya</br>
                14. Video tidak melanggar HAKI, tidak mengandung unsur SARA dan pornografi</br>
                15. Seluruh konten/isi video merupakan tanggung jawab peserta/pembuat. Apabila
                dikemudikan hari terjadi gugatan hak cipta, panitia tidak bertanggung jawab</br>
                16. Persyaratan file peserta:</br>
                a. Resolusi : Minimal 720p</br>
                b. Aspect Ratio :16:9</br>
                c. Format : MOV atau mp4</br>
                17. Peserta wajib memperhatikan copyright Ketika memilih gambar, music atau
                instrument</br>
                18. Semua Karya menjadi hak milik panitia</br>
                19. Film yang telah dikirmkan tidak boleh dotarik atau diambil Kembali</br>
                20. Keputusan hasil penjurian bersifat mutlak dan tidak dapat diganggu gugat</br>
                21. Panitia berhak mendiskualifikasi karya yang melanggar ketentuan</br>
              </p>
            </div>
            <div class="form_input" style="margin-bottom: 4rem;">
              <h3>Saya memahami dan ingin berpartisipasi</h3>
              <div style="display: flex;">
                <input required type="checkbox" name="Paham_dan_ingin_berpartisipasi"
                  placeholder="Saya memahami dan ingin berpartisipasi" id="id_Paham_dan_ingin_berpartisipasi" style="
                display: inline;
                width: auto;
                height: auto;
                padding: auto;
                line-height: auto;
                color: auto;
                background: auto;
                border: auto;
                border-radius: auto;
                margin-right: 1rem;">
                <p>Ya</p>
              </div>
            </div>
            <div>
              <h4 style="margin: 2rem 0">
                Lomba Short Movie dikenakan biaya sebesar 💳: Rp60.000/team
                Silahkan melakukan pembayaran melalui rekening berikut: Mandiri 1270006135071 A/N fero
                </br>
                </br>
                NOTE: silahkan gabung ke link group WhatsApp yang disediakan SETELAH submit Form ini
              </h4>
            </div>
            <div class="form_input">
              <h3>Upload Bukti Pembayaran</h3>
              {{ form.Bukti_Transaksi }}
            </div>
            <div>
              <h4 style="margin: 2rem 0">
                Silahkan upload foto kartu pelajar atau screenshoot NISN siswa aktif
              </h4>
            </div>
            <div class="form_input">
              <h3>Upload Bukti Pelajar</h3>
              {{ form.Bukti_Pelajar }}
            </div>

            <div class="form_input_btn text-center mb-40">
              <h4>
                Pastikan anda telah mengisi semua kolom diatas dengan data yang benar
              </h4>
              </br>
              <button type="submit" class="btn btn-link" style="z-index: 0;">
                Daftar
                <img width="20" height="20" src="{% static '/itech/assets/img/icon/arrrow-icon.webp' %}" alt="" />
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
  <!-- contact section end -->
</div>
<!-- page wrapper end -->
{% endblock %}

templates/itech/daftar-sukses-shortmovie.html
{% extends 'itech/base.html' %}
{% load static %}

{% block title %}
I-Tech | Daftar Sukses
{% endblock %}

{% block body-bg %}
{% static '/itech/assets/img/bg/body-bg2.webp' %}
{% endblock %}

{% block content %}

<!-- breadcrumbs area start -->
<div class="breadcrumbs_aree breadcrumbs_bg mb-140"
  data-bgimg="{% static '/itech/assets/img/bg/breadcrumbs-bg.webp' %}">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="breadcrumbs_text text-center">
          <h1>Daftar Sukses</h1>
          <ul class="d-flex justify-content-center">
            <li><a href="index.html">Home </a></li>
            <li><span>//</span></li>
            <li>Daftar Sukses</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- breadcrumbs area end -->

<!-- gaming  world section start -->
<section class="gaming_world_section mb-140">
  <div class="container">
    <div class="section_title text-center wow fadeInUp mb-60" data-wow-delay="0.1s" data-wow-duration="1.1s">
      <h3>
        Group Whatsapp Short Movie </br> <a
          href="https://chat.whatsapp.com/GRJFXXIWoZh4eUlu57eVix">https://chat.whatsapp.com/GRJFXXIWoZh4eUlu57eVix</a>
      </h3>
    </div>
  </div>
</section>
<!-- gaming  world section end -->

{% endblock %}

templates/itech/daftar-valorant.html
{% extends 'itech/base.html' %}
{% load static %}

{% block title %}
I-Tech | Daftar Valorant
{% endblock %}

{% block body-bg %}
{% static '/itech/assets/img/bg/body-bg2.webp' %}
{% endblock %}

{% block content %}
<!-- breadcrumbs area start -->
<div class="breadcrumbs_aree breadcrumbs_bg mb-140"
  data-bgimg="{% static '/itech/assets/img/bg/breadcrumbs-bg.webp' %}">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="breadcrumbs_text text-center">
          <h1>Daftar</h1>
          <ul class="d-flex justify-content-center">
            <li><a href="index.html">Home </a></li>
            <li><span>//</span></li>
            <li>Daftar</li>
            <li><span>//</span></li>
            <li>Valorant</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- breadcrumbs area end -->
<!-- page wrapper start -->
<div class="page_wrapper">
  <!-- contact section start -->
  <section class="contact_page_section mb-140">
    <div class="container">
      <div class="row justify-content-between align-items-center mb-n50">
        <div class="col-md-8 col-12 mx-auto mb-50">
          <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="section_title text-center mb-60">
              <h2>Daftar Valorant</h2>
              </br>
              <h4>
                Silahkan isi semua kolom dibawah dengan data yang benar
              </h4>
            </div>
            <div class="form_input">
              {{ form.Nama_Tim }}
            </div>
            <div class="form_input">
              {{ form.Nomor_Whatsapp_dan_Line }}
            </div>
            <div class="form_input">
              {{ form.Nomor_Whatsapp_dan_Line_opsional }}
            </div>
            <div class="form_input">
              {{ form.Player_1 }}
            </div>
            <div class="form_input">
              {{ form.Nama_Lengkap_atau_Nama_Asli_1 }}
            </div>
            <div class="form_input">
              {{ form.Player_2 }}
            </div>
            <div class="form_input">
              {{ form.Nama_Lengkap_atau_Nama_Asli_2 }}
            </div>
            <div class="form_input">
              {{ form.Player_3 }}
            </div>
            <div class="form_input">
              {{ form.Nama_Lengkap_atau_Nama_Asli_3 }}
            </div>
            <div class="form_input">
              {{ form.Player_4 }}
            </div>
            <div class="form_input">
              {{ form.Nama_Lengkap_atau_Nama_Asli_4 }}
            </div>
            <div class="form_input">
              {{ form.Player_5 }}
            </div>
            <div class="form_input">
              {{ form.Nama_Lengkap_atau_Nama_Asli_5 }}
            </div>
            <div class="form_input">
              {{ form.Player_6 }}
            </div>
            <div class="form_input">
              {{ form.Nama_Lengkap_atau_Nama_Asli_6 }}
            </div>
            <div class="form_input" style="margin-top: 4rem;">
              <h3>Peraturan Lomba</h3>
              <p>
                1. Biaya pendaftaran Rp. 50.000,00 per tim.</br>
                2. Wajib mengikuti technical meeting sebagai persyaratan daftar ulang dan konfirmasi.</br>
                3. Nama username Riot ID setelah didaftarkan tidak boleh diganti apabila ada pergantian peserta tidak
                dapat memasuki ruangan lomba.</br>
                4. Peserta yang berada di satu tim boleh berasal dari berbagai SMA/MA/Sederajat atau Perguruan
                Tinggi.</br>
                5. Peserta tidak boleh berkata dan melontarkan kalimat yang bersifat menyinggung SARA di chat maupun di
                discord, jika terbukti melakukan tindakan SARA akan didendakan sebesar Rp30.000,00.</br>
                6. Peserta dilarang menggunakan cheat, macro, maupun alat curang yang lainnya.</br>
                7. Panitia tidak bertanggung jawab atas masalah jaringan internet.</br>
              </p>
            </div>
            <div class="form_input" style="margin-bottom: 4rem;">
              <h3>Saya memahami dan ingin berpartisipasi</h3>
              <div style="display: flex;">
                <input required type="checkbox" name="Paham_dan_ingin_berpartisipasi"
                  placeholder="Saya memahami dan ingin berpartisipasi" id="id_Paham_dan_ingin_berpartisipasi" style="
                display: inline;
                width: auto;
                height: auto;
                padding: auto;
                line-height: auto;
                color: auto;
                background: auto;
                border: auto;
                border-radius: auto;
                margin-right: 1rem;">
                <p>Ya</p>
              </div>
            </div>
            <div>
              <h4 style="margin: 2rem 0">
                Lomba Valorant dikenakan biaya sebesar 💳: Rp50.000/team
                Silahkan melakukan pembayaran melalui rekening berikut: Mandiri 1270006135071 A/N fero
                </br>
                </br>
                NOTE: silahkan gabung ke link group WhatsApp yang disediakan SETELAH submit Form ini
              </h4>
            </div>
            <div class="form_input">
              <h3>Upload Bukti Transaksi</h3>
              {{ form.Bukti_Transaksi }}
            </div>
            <div>
              <h4 style="margin: 2rem 0">
                Silahkan upload foto kartu pelajar atau screenshoot NISN siswa aktif
              </h4>
            </div>
            <div class="form_input">
              <h3>Upload Bukti Pelajar</h3>
              {{ form.Bukti_Pelajar }}
            </div>

            <div class="form_input_btn text-center mb-40">
              <h4>
                Pastikan anda telah mengisi semua kolom diatas dengan data yang benar
              </h4>
              </br>
              <button type="submit" class="btn btn-link" style="z-index: 0;">
                Daftar
                <img width="20" height="20" src="{% static '/itech/assets/img/icon/arrrow-icon.webp' %}" alt="" />
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
  <!-- contact section end -->
</div>
<!-- page wrapper end -->
{% endblock %}

templates/itech/navbar.html
{% load static %}
<header>
  <a class="logo" href="/itech"><img src="{% static '/itech/assets/img/logoitech.png' %}" alt="logo"></a>
  <nav>
      <ul class="nav__links">
          <li><a href="/itech">Home</a></li>
          <li><a href="/itech/about">Tentang</a></li>
          <li><a href="/itech/juknis">Juknis</a></li>
          <li><a href="/itech/timeline">Timeline</a></li>
      </ul>
  </nav>
  <a class="cta1" href="/itech/daftar">Daftar</a>
  <p class="menu cta1">Menu</p>
</header>
<div class="overlay">
  <a class="close">&times;</a>
  <div class="overlay__content">
      <a href="/itech/home">Home</a>
      <a href="/itech/daftar">Daftar</a>
      <a href="/itech/about">Tentang</a>
      <a href="/itech/juknis">Juknis</a>
      <a href="/itech/t">Timeline</a>

  </div>
</div>